language: c

python:
  - "2.7"

sudo: false

addons:
  apt:
    packages:
      - socat

matrix:
  include:
    - compiler: ": Lua51"
      env: LUA="lua 5.1"
    - compiler: ": Lua52"
      env: LUA="lua 5.2"
    - compiler: ": Lua53"
      env: LUA="lua 5.3"
    - compiler: ": LuaJIT20"
      env: LUA="luajit 2.0"
    - compiler: ": LuaJIT21"
      env: LUA="luajit 2.1"

cache:
  directories:
    - here
    - $HOME/.cache/pip

branches:
  only:
    - master

before_install:
  - export CC=gcc
  - pip install --user hererocks
  - hererocks here -r^ --$LUA
  - export PATH=$PATH:$PWD/here/bin

install:
  - luarocks make rockspecs/rs232-scm-0.rockspec

before_script:
  - luarocks show lluv       || bash .travis/setup_uv.sh
  - luarocks show lluv       || luarocks install lluv UV_DIR=$TRAVIS_BUILD_DIR/libuv
  - luarocks show lzmq-timer || luarocks install lzmq-timer
  - luarocks show lunitx     || luarocks install lunitx

script:
  - cd $TRAVIS_BUILD_DIR/bindings/lua/test
  - lua -lrs232 -v
  - lua test_socat.lua

notifications:
  email:
    on_success: change
    on_failure: always
